### ISSUE TITLE
Salt installation handlers for other OS

### ISSUE THREAD

**Issue by akoumjian** [vmware-archive/salty-vagrant#1]
This tool currently relies on assuming the user is provisioning an Ubuntu virtual machine. There need to be handlers that check the virtual machine for the type distribution and then bootstrap salt with the appropriate package or source management tools.

Suggest looking at the salt/pkg module for some guidance on how this is done.

**Comment by Gussy** [comment]
I've started a new branch on my repo adding support for multiple operating systems. Hopefully this will increase the chances of salty-vagrant being included with vagrant by default, which is something I would like to see.

Installation of the salt binaries is handled by a bootstrapping shell script, written in plain posix sh. The script is bundled with the gem and copied to the VM by the salt provisioner, then run on the target VM.

The script is straight forward, it's probably better to check the source than to explain it. Currently Ubuntu 10/11/12 and Debian 6 are supported and tested, adding more operating systems is simple enough, they just need to be tested by someone who is familiar with them.

One scenario this solution doesn't cover is Windows, which Salt supports. I debated building the bootstrapping script in Python or Ruby, but chose plan shell as it should be available on all bare Linux installs and was quick to develop. Ideally the bootstrapping script would be in Ruby like the provisioner, since vagrant guarantees it's will exist, however I don't know enough Ruby to make that work well. The linux commands used for finding the operating system type and version will be the same for any language, so changing to a Python or Ruby script would not be too hard as half the work is in crafting the those commands.

Please try it out and let me know what your thoughts :)

Gus

**Comment by thatch45** [comment]
Thanks for the help here @Gussy! I will of course deffer to @akoumjian as to where he sees this going :)

**Comment by akoumjian** [comment]
Hi @Gussy, this is great. I have been meaning to start on this for a while and glad you have gotten the ball rolling here.  I won't be able to test this until later today. 

I think the shell script makes the most sense for now. If only Vagrant were built in Python, this would be worlds easier with the platform library (and as far as I can tell, Ruby does not have an equivalent lib). 

As far as Windows, perhaps there is a way to triage this using Ruby and run a bat file or something.

Anyway, thanks! I will take a deeper look at this later today. @thatch45 , I would appreciate your input or anyone else's  experience in detecting other distros and how best to bootstrap salt with them (in particular I am thinking CentOS / Fedora ).

**Comment by thatch45** [comment]
Sounds good, I will let you know!

**Comment by akoumjian** [comment]
After thinking about this some more, I would like to use a similar approach but executing a Python script instead of a bash script. Using Python will make it easier to triage a variety of OSs by using the platform library and in today's world will actually be slightly more portable. I've started work on it this morning and should have something up later today.

I appreciate the work and I'll use the same general method to execute the bootstrapping script.

**Comment by benhosmer** [comment]
This is really a great addition. I tried using salty on CentOS 6 briefly today, and while the vm boots, and says that it is installing SALT, it never got installed. This is after another manual update of vbox-guest additions using the [CentOS](https://vagrant-centos-6.s3.amazonaws.com/centos-6.box) while broswing [vagrantbox.es](http://www.vagrantbox.es/).

I didn't get much further than that though as far as investigating what was going on. I then saw work on this issue and decided to wait.

**Comment by Gussy** [comment]
A python version sounds good, I'm all for that. Apparently the platform library was new in Python 2.3 so that should cover most OSes.

I looked into windows support and decided it's nowhere near worth worrying about for a while yet. Vagrant support for windows is sketchy at best from what I can see, so there isn't much point in going out of our way to support it.

@benhosmer CentOS isn't supported in the latest version of the bootstrapping fork. I have it working locally but if we're moving to Python there isn't much sense in committing it. Adding support for new OSes is easy enough, it just needs someone to test it.

@thatch45 Regardless of shell or python, this bootstrapping script could become a reliable and well supported method of installing Salt Stack. With the shell script you could do `curl https://install.saltstack.org | /bin/sh`. The same idea should work for python. A one line installer would be great for people wanting to try out Salt Stack.

**Comment by thatch45** [comment]
A single install script would also help a great deal with salt-cloud. Right now salt-cloud uses distro specific scripts to get salt installed:
https://github.com/saltstack/salt-cloud/tree/develop/saltcloud/deploy

**Comment by akoumjian** [comment]
I love the idea. I'm working on it right now. I should have an initial
release for vagrant tonight or tomorrow.

**Comment by thatch45** [comment]
I am excited, we will be able to integrate this on many levels!

**Comment by benhosmer** [comment]
I can't wait to see how you do it.

**Comment by akoumjian** [comment]
I have pushed to develop a preliminary bootstrap script. The only problem I've run into so far is that it looks like Arch does not support python 2 out of the box; something I had not expected. If this is the case I may go with @Gussy's bash approach. I just hate to redo the work of sniffing out each distro and the myriad of ways they choose to present themselves.

Open to suggestions.

**Comment by thatch45** [comment]
Yes, that is a bummer, a number of distros don't have python by default, like FreeBSD. So we might have to make this default to sh

**Comment by Gussy** [comment]
That's a shame, at least all is not lost. You could detect the presence of python 2.3+ from ruby to target the right type of script, but I don't think maintaining sh and python scripts is really very desirable at all. Detecting the different operating systems (in sh) is simple enough if you follow a process of elimination like the script in my branch does.

In shell, the architecture (linux/bsd/darwin) can be found through uname first up, then the distribution is easy enough to detect since you know where to look. All linux distros (that I know of) have an /etc/*-release file that you can read from to get the OS version, linux goes one further with lsb-release.

Detecting the OS isn't the difficult part, it's the testing of each and every version of each operating system that's the time consuming part. It might be best to just include support for the popular distro/release combinations and encourage pulls/issues when people run into something unsupported.

**Comment by thatch45** [comment]
As much as I would prefer a python script, I think that it would be best if we wrote a single universal sh install script. The script could be used for salty-vagrant, salt-cloud, and a myriad of other applications. The only place it would not work would be Windows.

**Comment by akoumjian** [comment]
Okay, I've been swayed. @Gussy, will you issue a pull request to develop?

**Comment by benhosmer** [comment]
I'm assuming from looking at the recent merge that this isn't complete?

I went through the bootstrap.sh script, and it doesn't look like it changed to include at least RHEL/CentOs

I've started adding some like this:

elif [ -f /etc/redhat-release ] ; then
        OS=$(redhat_release -si)
        CODENAME=$(redhat_release -sc)
        log "Installing for Redhat/CentOS"
        do_with_root yum update
        do_with_root yum --enablerepo=epel-testing install salt
        do_with_root yum update
        do_with_root yum install salt-minion

Should I continue or is @Gussy doing the same thing?

**Comment by akoumjian** [comment]
Correct. I was hoping to update it with both more distros and also the
develop options, but haven't had time. Feel free to do it and do a pull
request. That why this is still in 'develop'. When I feel like we have a
good initial set of distros and features (dev mode) I will do a version
bump and update master.

**Comment by benhosmer** [comment]
Okay, great.

I'll try to maybe get something for RedHat/CentOS based distributions in
there as well.

I've really not familiar with SUSE or Arch though.

On Tue, Sep 25, 2012 at 4:28 PM, Alec Koumjian notifications@github.comwrote:

> Correct. I was hoping to update it with both more distros and also the
> develop options, but haven't had time. Feel free to do it and do a pull
> request. That why this is still in 'develop'. When I feel like we have a
> good initial set of distros and features (dev mode) I will do a version
> bump and update master.
> 
> On Tue, Sep 25, 2012 at 1:19 PM, Ben Hosmer notifications@github.comwrote:
> 
> > I'm assuming from looking at the recent merge that this isn't complete?
> > 
> > I went through the bootstrap.sh script, and it doesn't look like it
> > changed to include at least RHEL/CentOs
> > 
> > I've started adding some like this:
> > 
> > elif [ -f /etc/redhat-release ] ; then
> > OS=$(redhat_release -si)
> > CODENAME=$(redhat_release -sc)
> > log "Installing for Redhat/CentOS"
> > do_with_root yum update
> > do_with_root yum --enablerepo=epel-testing install salt
> > do_with_root yum update
> > do_with_root yum install salt-minion
> > 
> > Should I continue or is @Gussy https://github.com/Gussy doing the
> > same
> > thing?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/saltstack/salty-vagrant/issues/1#issuecomment-8868648>.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salty-vagrant/issues/1#issuecomment-8868960.

## 

Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by RoboTeddy** [comment]
@benhosmer there might be some hints here: https://github.com/saltstack/salt-cloud/tree/develop/saltcloud/deploy

**Comment by benhosmer** [comment]
Thanks, that definitely should speed things up a bit.

On Tue, Sep 25, 2012 at 5:54 PM, Ted notifications@github.com wrote:

> @benhosmer https://github.com/benhosmer there might be some hints here:
> https://github.com/saltstack/salt-cloud/tree/develop/saltcloud/deploy
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/saltstack/salty-vagrant/issues/1#issuecomment-8871751.

## 

Ben Hosmer

Brevard Tech - Brevard County Florida's Tech User Group
http://www.brevardtech.org

Drupal Developer
http://www.radarearth.com

321.252.9581

**Comment by akoumjian** [comment]
@Gussy if you would be so kind, please take a look at https://github.com/saltstack/salty-vagrant/blob/rearrange/scripts/bootstrap-salt-minion.sh

I am attempting to add initial support for installing from git, but something about the way `do_with_root` works is causing the `cd` commands to not take hold once the next command is issued (https://github.com/saltstack/salty-vagrant/blob/rearrange/scripts/bootstrap-salt-minion.sh#L95)

I am not very fluent with bash scripting, so perhaps you have a suggestion. I tried issuing the commands using `&&` but with no success.

**Comment by thatch45** [comment]
Looks like you are following my lead, I am doing this in salt-cloud to allow us to test from git out on cloud systems.

**Comment by akoumjian** [comment]
It was a requested feature. I am stealing form the salt-cloud scripts. :-)

**Comment by thatch45** [comment]
Glad I can help, once these are all cleaned up we should be able to merge them :)

**Comment by Gussy** [comment]
I'll have a better look at this tonight, but just a quick thought for now.
For installing from git, could we use `sudo pip install git+https://github.com/saltstack/salt.git` ?

**Comment by thatch45** [comment]
Yes, but only if we have an assurance that pip will be available. In the case of salt-cloud pip is never available, this is the same problem as python not being available and forcing us to use bash

**Comment by s0undt3ch** [comment]
Need some clarification for #19. Which shell is considered installed in most distros? Which should our script use?

Does the install script need to run perfectly using plain sh?

Even using shell to bootstrap seems hard to please every distro flavour...

**Comment by benhosmer** [comment]
I think the idea is everything will work as perfectly as possible in plain shell. We talked briefly earlier about moving the install script to a python script, but some distros don't even have that by default.

It is a tough problem to solve with the myriad of BSDs, Linux flavors etc.

**Comment by s0undt3ch** [comment]
There's already support for other distributions. If the one you're after is not found, adding support for it has been made pretty simple and a different ticket should be opened. Closing this ticket.
