### ISSUE TITLE
Hangs on boot after highstate on CentOS 6.3

### ISSUE THREAD

**Issue by alecthomas** [vmware-archive/salty-vagrant#54]
Whenever I issue vagrant up, salt or vagrant+ssh hangs at the end of the salt.highstate run and never returns to the console.

The only way to return to control is to ^C a couple of times.

**Comment by benhosmer** [comment]
I had a few issues after one of the recent updates with CentOS 6.3, but I haven't encountered this lately. Are your guest additions up to date? I seem to remember that being a sticky issue sometimes.

I'm going to try it on one of my CentOS boxes and see if I can duplicate this, since I haven't used it in a while.

**Comment by retr0h** [comment]
If using masterless be sure your minion conf has `file_client: local` as per https://github.com/saltstack/salty-vagrant.  I ran into this problem not too long ago.

**Comment by iurquiza** [comment]
I am using Vagrant 1.5.1.
I want to run a vagrant box with a salt masterless set up.
I have 'salt.minion_config' set to point to the minion file.
Inside the 'minion' I have 'file_client: local'.
When I run 'vagrant provision' it hangs in 'Calling state.highstate...'
I have 'salt.verbose = true', it shows no output
I am pretty sure it hangs because the '--local' flag is missing.
When I kill the hanging process and 'vagrant ssh' I run
'sudo salt-call -l debug state.highstate', and I get the following:
[ERROR ] This master address: 'salt' was previously resolvable but now fails to resolve! The previously resolved ip addr will continue to be used
When I run:
sudo salt-call --local -l debug state.highstate
everything works fine.
Is there a work around to have 'vagrant provision' do the salt provisioning for a masterless setup?
Is there a way to pass the '--local' flag to the salt-call executed by vagrant?
