### ISSUE TITLE
Hangs on message "Calling state.highstate... (this may take a while)"

### ISSUE THREAD

**Issue by jehoshua02** [vmware-archive/salty-vagrant#67]
When running highstate manually timed around 4 minutes:

``` bash
time sudo salt-call --local state.highstate
```

But running via vagrant-salt hangs for more than 8 minutes, saying:

``` console
Calling state.highstate... (this may take a while)
```

**Comment by akoumjian** [comment]
You can use the `salt.verbose` flag to see what is going on.

**Comment by jehoshua02** [comment]
I am using `salt.verbose`, but I think that only affects the salt installation?

**Comment by akoumjian** [comment]
No, it should be outputting the highstate output. https://github.com/saltstack/salty-vagrant/blob/develop/lib/vagrant-salt/provisioner.rb#L230

There shouldn't be any difference considering that vagrant-salt is just calling "salt-call state.highstate". You do have file_client: local set in your minion config, right?

**Comment by jehoshua02** [comment]
Sorry, I'm brand new to salt. Somebody else provided the salt configs that I'm using. Here is my Vagrantfile:

``` ruby
  config.vm.synced_folder $submodules + "/ksl-vagrant/salt", "/srv/salt"
  config.vm.provision :salt do |salt|
    salt.bootstrap_options = "-P"
    salt.verbose = true
    salt.run_highstate = true
  end
```

There is a minion.conf in the salt root. I'm guessing salt will read it without me telling it to. And the minion.conf does have `file_client: local` set.

I've been changing things, trying this, trying that. I'll revert things and try again, just to be sure.

**Comment by akoumjian** [comment]
Ah, okay. Well then you're almost there! You probably want to include that minion config by passing `salt.minion_config = path/to/minion.conf`

**Comment by jehoshua02** [comment]
Oh, yeah, this is on vagrant-salt version 0.4.0 ... if that helps.

**Comment by jehoshua02** [comment]
The salt root is mounted into "/srv/salt". The minion.conf is right inside that. Do I still need the `salt.minion_config` in my Vagrantfile?

**Comment by jehoshua02** [comment]
No debug. Still hanging. Not sure what else to do.

**Comment by akoumjian** [comment]
Yes, you still need to point `salt.minion_config` to it. 

I think what's happening is that it is calling salt-call state.highstate and without the minion config telling it to go local, it is looking for a default salt master.

You'll know if you run `salt-call state.highstate` without the local flag on the minion and see if it hangs similarly.

**Comment by jehoshua02** [comment]
Indeed, it does hang without `--local` inside the box. Adding minion config option and trying again.

**Comment by jehoshua02** [comment]
Nice. That did it. Thanks!

**Comment by ejo** [comment]
Thanks for this.  Setting `salt.minion_config` explicitly in my Vagrantfile was the one diff between what works for Virtualbox 4.2 and Vagrant 1.3.x on Ubuntu 13.04, and what worked for Virtualbox 4.1 and Vagrant 1.0.x on Ubuntu 12.04.  The older setup worked without needing this to be set.  And it was even possible to upgrade each of these packages one at a time from my previously working stack and still have a working stack.  But when I attempted to rebuild my whole machine from scratch at latest versions, I struck this same issue.  Thanks again for the fix.

**Comment by iurquiza** [comment]
I am using Vagrant 1.5.1.
I want to run a vagrant box with a salt masterless set up.
I have 'salt.minion_config' set to point to the minion file.
Inside the 'minion' I have 'file_client: local'.
When I run 'vagrant provision' it hangs in 'Calling state.highstate...'
I have 'salt.verbose = true', it shows no output
I am pretty sure it hangs because the '--local' flag is missing.
When I kill the hanging process and 'vagrant ssh' I run
'sudo salt-call -l debug state.highstate', and I get the following:
[ERROR ] This master address: 'salt' was previously resolvable but now fails to resolve! The previously resolved ip addr will continue to be used
When I run:
sudo salt-call --local -l debug state.highstate
everything works fine.
Is there a work around to have 'vagrant provision' do the salt provisioning for a masterless setup?
Is there a way to pass the '--local' flag to the salt-call executed by vagrant?

**Comment by jehoshua02** [comment]
@iurquiza Here is a working Vagrant-Salt environment I put together a while ago. Maybe looking at it will help you figure it out:

https://github.com/jehoshua02/salty-vagrant-lamp-dev

Here's the version info and plugins I'm using:

``` bash
$ VBoxManage --version
4.3.8r92456
$ vagrant --version
Vagrant 1.4.3
$ vagrant plugin list
vagrant-vbguest (0.10.0)
```

One thing that tripped up my team was the vagrant-salt plugin. The latest versions of vagrant already have salt support built in, so the plugin I guess creates conflicts.

**Comment by iurquiza** [comment]
Thanks @jehoshua02. I was using vagrant's built in salt provisioning system. When I installed the salty-vagrant plugin everything worked fine. I believe vagrant must be using an outdated version of salty-vagrant. They link directly to salty-vagrant's github page at the bottom of http://docs.vagrantup.com/v2/provisioning/salt.html. By the way, thanks for the link to your salty-vagrant-lamp-dev environment. It is almost exactly what I wanted to accomplish; I will be using it as a guide.

**Comment by jehoshua02** [comment]
@iurquiza glad I could help!

**Comment by v6** [comment]
Has anyone in this thread added an issue for this to Vagrant?

**Comment by iurquiza** [comment]
I don't recall if I added an issue, but check [https://github.com/mitchellh/vagrant/issues/3296](https://github.com/mitchellh/vagrant/issues/3296) out.
Since Vagrant now uses its own Salt provisioning system you would have to add the issue on that repository. Even though [https://docs.vagrantup.com](https://docs.vagrantup.com) links to salty-vagrant the implementations are different. I suggested a fix, but since I am not proficient in Ruby I did not submit a pull request, as there is probably a better way to implement the fix.
